# Generated by Django 3.1.5 on 2021-01-20 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('meta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TargetUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('time_to_work', models.DateTimeField(default=datetime.datetime(2021, 1, 21, 1, 33, 50, 701679))),
            ],
        ),
    ]
