# Generated by Django 3.1.5 on 2021-01-20 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webparser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targeturl',
            name='time_to_work',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 1, 50, 48, 651240)),
        ),
    ]
