# Generated by Django 3.1.5 on 2021-01-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webparser', '0004_auto_20210121_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targeturl',
            name='time_to_work',
        ),
    ]
